import Head from 'next/head';
import styled from 'styled-components';
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles';
import Cards from '../components/cards';

import MainTimer from '../components/mainTimer';

const TestContainer = styled.div`
  width: 300px;
  height: 300px;
`;

const Home = () => (
  <Container>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Main>
      <Title>
        Welcome to
        {' '}
        <a href="https://nextjs.org">Next.js!</a>
      </Title>

      <TestContainer>
        <MainTimer />
      </TestContainer>

      <Description>
        Get started by editing
        <CodeTag>pages/index.tsx</CodeTag>
      </Description>

      <Cards />
    </Main>
  </Container>
);

export default Home;
