export const dryadBark = '#37352f'; // light theme string color
export const white = '#ffffff'; // light theme component color
export const gray90 = '#e5e5e5';
export const errigalWhite = '#f6f6f9'; // light theme background color
export const gainsboro = '#d9d9d9'; // light theme border color
export const coralRed = '#f93e3d'; // common danger color
export const roseMadder = '#e03736';
export const tartanRed = '#ae2b2a';
export const translucentUnicorn = '#fcecee';
export const petalBloom = '#f9d6da';
export const softPetals = '#e9f6ef';
export const vegetation = '#48cd90'; // common info color
export const mintFlash = '#daf5e8';
export const viridian = ' #328f64';
export const mingGreen = '#40b881';
export const exquisiteEmerald = '#288a60';
export const stonewallGrey = '#c3c2c1';
export const astrograniteDebris = '#3b414a'; // dark theme border color
export const aswadBlack = '#141519'; // dark theme background color
export const washedBlack = '#202528'; // dark theme component background color
export const whiteSmoke = '#F5F5F5'; // light theme overlay color
export const carbon = '#333333'; // dark theme overlay color
